### ISSUE TITLE
How to use another default font-family?

### ISSUE THREAD

**Issue by nextlevelshit** [JensErat/pandoc-scrlttr2#12]
I am trying hardly to change the default font family. Could you give some advice @JensErat, please?

**Comment by JensErat** [comment]
Did you try setting `$fontfamily`? From `scrlttr2.latex`, and also used in most other Pandoc LaTeX templates:

```latex
$if(fontfamily)$
\usepackage[$for(fontfamilyoptions)$$fontfamilyoptions$$sep$,$endfor$]{$fontfamily$}
$else$
\usepackage{lmodern}
$endif$
```

You should also be able to include the matching font setup options in a `.lco` file, which you will likely be doing anyway to preset `from` variables.

If you have issues with font selection because of `pdflatex` -- you can switch to another LaTeX engine by passing normal `pandoc` options (`--latex-engine=pdflatex|lualatex|xelatex`).

**Comment by nextlevelshit** [comment]
Thanks @JensErat!
The main problem was caused by the latex engine `pdflatex`. Honestly I could not find how to change the main font, but I could change it at least to sans-serif:

```latex
  \renewcommand{\familydefault}{\sfdefault} % set sans-serif as default font family
```

**Comment by JensErat** [comment]
You can add such modification in letter class option files, as described in the readme.
